export const ROUTES = {
  HOME: '/',
  AGREEMENT: '/agreement',
  LOGIN: '/login',
  REGISTER: '/register',
  SEARCH: '/search',
  SETTINGS: '/settings',
  COLLECTION: '/collection:/id',
  PLAYLIST: '/playlist/:id',
  MY_PROFILE: '/profile/me',
  PROFILE: '/profile/:id',
  SUBSCRIPTION_ACTIVE: '/subscription/active',
  SUBSCRIPTION_PURCHASE: '/subscription/purchase',
  UPLOAD_COLLECTION: '/upload/collection',
  UPLOAD_AUDIO: '/upload/audio',
};
